apiVersion: v1
kind: ConfigMap
metadata:
  name: say-hello
data:
  to: world
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: hello
spec:
  organization: hashicorp-team-demo
  secretsMountPath: "/tmp/secrets"
  #sshKeyID: "sshkey-12345"
  module:
    source: "joatmon08/hello/random"
    version: "4.0.0"
  outputs:
    - key: my_pets
      moduleOutputName: list_of_pets
  variables:
    - key: hello
      value: rosemary
      sensitive: false
      environmentVariable: false
    - key: second_hello
      valueFrom:
        configMapKeyRef:
          name: say-hello
          key: to
      sensitive: false
      environmentVariable: false
    - key: secret_key
      sensitive: true
      environmentVariable: false
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true